### ISSUE TITLE
process killed as timeout reached (In HA 2021.7.2)

### ISSUE THREAD

**Issue by poudenes** [haberda/signal-addon#1]
Since update to latest HA: 2021.7.2 I see those errors:

```
2021-07-14 16:17:28 ERROR (SyncWorker_15) [homeassistant.components.signal_messenger.notify] process killed as timeout reached
2021-07-14 16:17:28 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall notify.signal_to_sister (c:3b8666508650253f82c827d7172605dc): message=Template("Jongejans GP, # 4, €: 4.99")>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 159, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 136, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 79, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 76, in send_message
    self._signal_cli_rest_api.send_message(message, self._recp_nrs, filenames)
  File "/usr/local/lib/python3.9/site-packages/pysignalclirestapi/api.py", line 83, in send_message
    raise exc
  File "/usr/local/lib/python3.9/site-packages/pysignalclirestapi/api.py", line 79, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

2021-07-14 18:17:27 ERROR (SyncWorker_1) [homeassistant.components.signal_messenger.notify] process killed as timeout reached
2021-07-14 18:17:27 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall notify.signal_to_sister (c:c433c1133a700e6b05b998ad58fc131d): message=Template("Le Pain Quotidien GP, # 2, €: 4.99")>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 159, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 136, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 79, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 76, in send_message
    self._signal_cli_rest_api.send_message(message, self._recp_nrs, filenames)
  File "/usr/local/lib/python3.9/site-packages/pysignalclirestapi/api.py", line 83, in send_message
    raise exc
  File "/usr/local/lib/python3.9/site-packages/pysignalclirestapi/api.py", line 79, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached
```

**Comment by haberda** [comment]
Are you running on an ARM device? It looks related to [this](https://github.com/bbernhard/signal-cli-rest-api/issues/145).

A new variable has been added to the latest release to up the timeout length.
