### ISSUE TITLE
Java Error When Using the Add-On, CLI (curl) Works

### ISSUE THREAD

**Issue by remygithub** [haberda/signal-addon#2]
- Calling `notify.signal` service results in the following Java error (see logs below).  
  - Add-on worked without issue until now
- Calling the REST api from console works as expected (register, message send/receive, groups, etc)

Error log:
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: components/signal_messenger/notify.py:76
First occurred: 1:00:14 AM (1 occurrences)
Last logged: 1:00:14 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Exception in thread "main" java.lang.NumberFormatException: For input string: "51196591+72" at java.lang.Long.parseLong(Long.java:692) at java.lang.Long.parseLong(Long.java:817) at org.whispersystems.signalservice.internal.contacts.crypto.ContactDiscoveryCipher.buildQueryData(ContactDiscoveryCipher.java:65) at org.whispersystems.signalservice.internal.contacts.crypto.ContactDiscoveryCipher.createDiscoveryRequest(ContactDiscoveryCipher.java:28) at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsers(SignalServiceAccountManager.java:425) at org.asamk.signal.manager.Manager.getRegisteredUsers(Manager.java:1601) at org.asamk.signal.manager.Manager.getSignalServiceAddresses(Manager.java:1568) at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1286) at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:101) at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:122) at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:15) at org.asamk.signal.App.handleLocalCommand(App.java:214) at org.asamk.signal.App.init(App.java:174) at org.asamk.signal.Main.main(Main.java:51)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 159, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 136, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 79, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 76, in send_message
    self._signal_cli_rest_api.send_message(message, self._recp_nrs, filenames)
  File "/usr/local/lib/python3.9/site-packages/pysignalclirestapi/api.py", line 83, in send_message
    raise exc
  File "/usr/local/lib/python3.9/site-packages/pysignalclirestapi/api.py", line 79, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: Exception in thread "main" java.lang.NumberFormatException: For input string: "51196591+72"
	at java.lang.Long.parseLong(Long.java:692)
	at java.lang.Long.parseLong(Long.java:817)
	at org.whispersystems.signalservice.internal.contacts.crypto.ContactDiscoveryCipher.buildQueryData(ContactDiscoveryCipher.java:65)
	at org.whispersystems.signalservice.internal.contacts.crypto.ContactDiscoveryCipher.createDiscoveryRequest(ContactDiscoveryCipher.java:28)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsers(SignalServiceAccountManager.java:425)
	at org.asamk.signal.manager.Manager.getRegisteredUsers(Manager.java:1601)
	at org.asamk.signal.manager.Manager.getSignalServiceAddresses(Manager.java:1568)
	at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1286)
	at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:101)
	at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:122)
	at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:15)
	at org.asamk.signal.App.handleLocalCommand(App.java:214)
	at org.asamk.signal.App.init(App.java:174)
	at org.asamk.signal.Main.main(Main.java:51)
```

**Comment by haberda** [comment]
I don't maintain the home assistant integration. This looks like a problem with that integration.

But it looks like home assistant is not receiving an expected response from the signal container.

I would check first if the home assistant integration is properly configured. Next, is it possible the safety number has changed with the recipient? If it has you have to use the CLI to confirm the safety number change.

**Comment by remygithub** [comment]
I can still send/receive messages using CLI (curl).  Safety numbers look fine on both ends.   
Signal integration config using `native_mode` and `AUTO_RECEIVE`.  The port number looks good as well as Home Assistant yaml.
**But I cannot send from Home Assistant using `notify.signal`**

**UPDATE...**
I updated the core system and comment ed out the group recipient (used `internal_id`) from the `recipients` list.  Only sending to single number for now...
**And it just started working again.....!!!!**
