### ISSUE TITLE
Java exception in 0.65

### ISSUE THREAD

**Issue by kezmdor** [haberda/signal-addon#74]
After updating to v0.65 no more messages could be sent. Downgraded to v0.64 and everything is back to normal operation.

Home Assistant 2022.11.5
Supervisor 2022.12.1
Operating System 9.3
Frontend 20221108.0 - latest

Logs:

`Logger: homeassistant.components.automation.testsignalmessenger
Source: components/signal_messenger/notify.py:104
Integration: Automatisierung (documentation, issues)
First occurred: 20:21:50 (2 occurrences)
Last logged: 20:21:50

TestSignalMessenger: Error executing script. Unexpected error for call_service at pos 1: Failed to load native library:sqlite-3.40.0.0-092410ba-a44b-41b8-b020-8af14cfc7e8a-libsqlitejdbc.so. osinfo: Linux/x86_64 java.lang.UnsatisfiedLinkError: Can't load library: /tmp/sqlite-3.40.0.0-092410ba-a44b-41b8-b020-8af14cfc7e8a-libsqlitejdbc.so at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:104) at java.lang.ClassLoader.loadLibrary(ClassLoader.java:54) at java.lang.Runtime.load0(Runtime.java:755) at java.lang.System.load(System.java:1953) at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280) at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237) at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350) at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68) at org.sqlite.core.NativeDB.load(NativeDB.java:63) at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278) at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65) at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19) at org.sqlite.JDBC.createConnection(JDBC.java:104) at org.sqlite.JDBC.connect(JDBC.java:77) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101) at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32) at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32) at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236) at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649) at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234) at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209) at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649) at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206) at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:28) at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:639) at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181) at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92) at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79) at org.asamk.signal.App.loadManager(App.java:355) at org.asamk.signal.App.handleLocalCommand(App.java:288) at org.asamk.signal.App.init(App.java:229) at org.asamk.signal.Main.main(Main.java:60) ERROR HikariPool - HikariPool-1 - Exception during pool initialization. java.sql.SQLException: Error opening connection at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281) at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65) at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19) at org.sqlite.JDBC.createConnection(JDBC.java:104) at org.sqlite.JDBC.connect(JDBC.java:77) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101) at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32) at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32) at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236) at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649) at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234) at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209) at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649) at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206) at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:28) at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:639) at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181) at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92) at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79) at org.asamk.signal.App.loadManager(App.java:355) at org.asamk.signal.App.handleLocalCommand(App.java:288) at org.asamk.signal.App.init(App.java:229) at org.asamk.signal.Main.main(Main.java:60) Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/usr/lib64:/lib64:/lib:/usr/lib] at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375) at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68) at org.sqlite.core.NativeDB.load(NativeDB.java:63) at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278) ... 30 common frames omitted Error loading state file for user XXXXXXXXXXXX: Failed to initialize pool: Error opening connection (PoolInitializationException)
While executing automation automation.testsignalmessenger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 258, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 234, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 109, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 104, in send_message
    self._signal_cli_rest_api.send_message(
  File "/usr/local/lib/python3.10/site-packages/pysignalclirestapi/api.py", line 221, in send_message
    raise exc
  File "/usr/local/lib/python3.10/site-packages/pysignalclirestapi/api.py", line 216, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: Failed to load native library:sqlite-3.40.0.0-092410ba-a44b-41b8-b020-8af14cfc7e8a-libsqlitejdbc.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: Can't load library: /tmp/sqlite-3.40.0.0-092410ba-a44b-41b8-b020-8af14cfc7e8a-libsqlitejdbc.so
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:104)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:54)
	at java.lang.Runtime.load0(Runtime.java:755)
	at java.lang.System.load(System.java:1953)
	at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)
	at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:104)
	at org.sqlite.JDBC.connect(JDBC.java:77)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
	at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
	at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)
	at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)
	at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)
	at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)
	at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)
	at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)
	at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)
	at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:28)
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:639)
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181)
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92)
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)
	at org.asamk.signal.App.loadManager(App.java:355)
	at org.asamk.signal.App.handleLocalCommand(App.java:288)
	at org.asamk.signal.App.init(App.java:229)
	at org.asamk.signal.Main.main(Main.java:60)
ERROR HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:104)
	at org.sqlite.JDBC.connect(JDBC.java:77)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)
	at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)
	at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)
	at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)
	at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)
	at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)
	at org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)
	at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)
	at org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)
	at org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:28)
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:639)
	at org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181)
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92)
	at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)
	at org.asamk.signal.App.loadManager(App.java:355)
	at org.asamk.signal.App.handleLocalCommand(App.java:288)
	at org.asamk.signal.App.init(App.java:229)
	at org.asamk.signal.Main.main(Main.java:60)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/usr/lib64:/lib64:/lib:/usr/lib]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
	... 30 common frames omitted
Error loading state file for user XXXXXXXXXX: Failed to initialize pool: Error opening connection (PoolInitializationException)
`

**Comment by haberda** [comment]
Which mode are you using?

If you are not using normal mode, what happens if you change it to that?

**Comment by BogoPo** [comment]
> Which mode are you using?
> 
> If you are not using normal mode, what happens if you change it to that?

I was having the same error while using native mode. Changing to normal mode fixed it for me. Thank you so much!

**Comment by kezmdor** [comment]
> Which mode are you using?
> 
> If you are not using normal mode, what happens if you change it to that?

I was on native mode as well. Normal mode and json-rpc mode are good, I will stay on json-rpc, since it is significantly faster.

**Comment by haberda** [comment]
Good to hear. This is an upstream issue with native mode then.
